### ISSUE TITLE
Production env

### ISSUE THREAD

**Issue by yasaricli** [tsepeti/tatsy#6]
* nodemon will not run in production environment.

**Comment by canyener** [comment]
* Discusssing environments, variables (if needed) and testing strategies before implementation might be a better approach.

**Comment by yasaricli** [comment]
Maybe as following:

add script:

```JS
{
  "scripts": {
    "start": "tatsy start",
    "build": "tatsy build",
  }
}
```

    export NODE_ENV=production
    yarn build

if production is **nodemon** and **watcher** will not work.

    yarn start


https://github.com/tsepeti/tatsy/blob/master/packages/tatsy/bin/tatsy#L11
